# Default values
# https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
usePassword: false
architecture: replication
auth:
  enabled: false
  sentinel: false
master:
  persistence:
    enabled: false
replica:
  persistence:
    enabled: false
  replicaCount: 2
sentinel:
  enabled: true
