apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
spec:
  releaseName: kafka
  chart:
    spec:
      chart: kafka
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "19.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    replicaCount: 2
    autoCreateTopicsEnable: false
    zookeeper:
      replicaCount: 2
    persistance:
      enabled: false
    provisioning:
      enabled: true
      topics:
      - name: organisation
        partitions: 1
        replicationFactor: 2
        ## https://kafka.apache.org/documentation/#topicconfigs
        config:
          max.message.bytes: 64000
          flush.messages: 1
      - name: playlist
        partitions: 1
        replicationFactor: 2
        config:
          max.message.bytes: 64000
          flush.messages: 1
      - name: track
        partitions: 1
        replicationFactor: 2
        config:
          max.message.bytes: 64000
          flush.messages: 1
      - name: user
        partitions: 1
        replicationFactor: 2
        config:
          max.message.bytes: 64000
          flush.messages: 1